services:
  webauthn-app:
    image: golang:1.23
    container_name: webauthn-app
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: webauthn-db
    environment:
      POSTGRES_USER: webauthn
      POSTGRES_PASSWORD: webauthnpassword
      POSTGRES_DB: webauthn_db
    ports:
      - "5555:5432"
    user: 501:501
    volumes:
      - db_data:/var/lib/postgresql/data
