services:
  webauthn-app:
    image: golang:1.23
    container_name: webauthn-app
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    develop:
      watch:
        - action: restart
          path: .
          target: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: webauthn-db
    environment:
      POSTGRES_USER: webauthn
      POSTGRES_PASSWORD: webauthnpassword
      POSTGRES_DB: webauthn_db
    env_file:
      - .env
    ports:
      - "5555:5432"
    user: 501:501
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
      - ./db_data/postgres:/db_data
      - ./db:/db

  redis:
    image: redis:6
    container_name: webauthn-redis
    ports:
      - "6379:6379"
    user: 501:501
    volumes:
      - ./db_data/redis:/data