services:
  webauthn-app:
    image: golang:1.23
    container_name: webauthn-app
    working_dir: /app
    volumes:
      - .:/app
    command: go run .
    develop:
      watch:
        - action: restart
          path: .
          target: /app
          ignore:
            - db_data/
            - db/
            - views/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  frontend:
    image: node:18-alpine
    container_name: webauthn-frontend
    working_dir: /app
    volumes:
      - ./views:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    develop:
      watch:
        - action: sync
          path: ./views/src
          target: /app/src
        - action: sync
          path: ./views/public
          target: /app/public
        - action: rebuild
          path: ./views/package.json
          target: /app/package.json
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080

  db:
    image: postgres:13
    container_name: webauthn-db
    environment:
      POSTGRES_USER: webauthn
      POSTGRES_PASSWORD: webauthnpassword
      POSTGRES_DB: webauthn_db
    env_file:
      - .env
    ports:
      - "5555:5432"
    user: 501:501
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
      - ./db_data/postgres:/db_data
      - ./db:/db

  redis:
    image: redis:6
    container_name: webauthn-redis
    ports:
      - "6379:6379"
    user: 501:501
    volumes:
      - ./db_data/redis:/data