CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS webauthn_user_id BYTEA UNIQUE,
ADD COLUMN IF NOT EXISTS webauthn_credential_id VARCHAR(255) UNIQUE,
ADD COLUMN IF NOT EXISTS webauthn_credential_public_key VARCHAR(255),
ADD COLUMN IF NOT EXISTS webauthn_sign_count INTEGER,
ADD COLUMN IF NOT EXISTS webauthn_displayname BYTEA UNIQUE;

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

DROP INDEX IF EXISTS idx_users_webauthn_id;

ALTER TABLE users
DROP COLUMN IF EXISTS webauthn_public_key,
DROP COLUMN IF EXISTS webauthn_id,
ALTER COLUMN webauthn_displayname TYPE VARCHAR(100),
ALTER COLUMN webauthn_user_id TYPE VARCHAR(100);